os: linux
  
language: go

go:
  - 1.13.x

# Add Docker service
services:
  - docker

script:   
  # Test the code
  - go test -v ./...
  # Build the code 
  - CGO_ENABLED=0 GOARCH=amd64 go build -o demo

  # Login to DockerHub
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  
  # Build the Docker image
  - docker build -f Dockerfile -t s1910595005/demo:latest ./
  
  # Retrieve Git SHA and re-tag Docker image 
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag s1910595005/demo:latest s1910595005/demo:$GIT_SHA

  # Push images to DockerHub
  - docker push s1910595005/demo:latest
  - docker push s1910595005/demo:$GIT_SHA
